### ISSUE TITLE
CPU频率动态显示

### ISSUE THREAD

**Issue by nxbxx504** [nxez/pi-dashboard#19]
我现在是个树莓派4B，发现CPU的频率是根据负载自动动态调整的，能不能cpu频率动态显示，现在只能手动刷新。

**Comment by anonymous-codecreator** [comment]
自己完整替换，已经汉化。

**Comment by anonymous-codecreator** [comment]
[Pi_Dashboard_ChnSimp.zip](https://github.com/spoonysonny/pi-dashboard/files/4498183/Pi_Dashboard_ChnSimp.zip)

**Comment by anonymous-codecreator** [comment]
自己完整替换，已经汉化。

**Comment by spoonysonny** [comment]
多谢各位。已经在 v1.1 版本中加入了这个特性。
